// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUHmzus0BAmlLOiEvs2DLU6AH6u9-6CTc',
    appId: '1:177315268958:web:dd96136980d556f7bf67cf',
    messagingSenderId: '177315268958',
    projectId: 'synthora-pos',
    authDomain: 'synthora-pos.firebaseapp.com',
    storageBucket: 'synthora-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5HfgB7bmZiB__qILBka56i8vtZTUo7E',
    appId: '1:177315268958:android:22a3e73a11a49ff8bf67cf',
    messagingSenderId: '177315268958',
    projectId: 'synthora-pos',
    storageBucket: 'synthora-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtEQecRfxuOYy7GCBs9J3EI_fWXr2flfs',
    appId: '1:177315268958:ios:686889512bc4f786bf67cf',
    messagingSenderId: '177315268958',
    projectId: 'synthora-pos',
    storageBucket: 'synthora-pos.firebasestorage.app',
    iosBundleId: 'com.synthora.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtEQecRfxuOYy7GCBs9J3EI_fWXr2flfs',
    appId: '1:177315268958:ios:873747cdab5030e1bf67cf',
    messagingSenderId: '177315268958',
    projectId: 'synthora-pos',
    storageBucket: 'synthora-pos.firebasestorage.app',
    iosBundleId: 'com.synthora.pos.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUHmzus0BAmlLOiEvs2DLU6AH6u9-6CTc',
    appId: '1:177315268958:web:4c262ed7ac04ec66bf67cf',
    messagingSenderId: '177315268958',
    projectId: 'synthora-pos',
    authDomain: 'synthora-pos.firebaseapp.com',
    storageBucket: 'synthora-pos.firebasestorage.app',
  );
}
